version: '3.2'

services:
  frontend: 
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    container_name: frontend
    depends_on:
      - "backend"
    environment:
    -  BACKEND_HOST=192.168.15.22
    -  BACKEND_PORT=8080
    ports:
      - "8000:8000"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: always 
    container_name: backend 
    ports:
      - "8080:8080/tcp"

networks:
  bexs:
    driver: bridge

volumes:
  bexs:
